name: Build, Lint and Test
run-name: CI initiated by ${{ github.actor }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_lint_test:
    name: hermes-proto - latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Rust toolchain
        run: |
          rustup update
      
      - name: Build
        run: cargo build --verbose

      - name: Lint
        run: cargo clippy

      - name: Test
        run: cargo test --verbose
